### PR TITLE
Send "stream-definition" regularly to client

### PR DESCRIPTION
**Pull request by kris-lab**
In a configurable time interval? 10 seconds?

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look

the output looks like that:
```
{
 "streaming": "event",
 "result": {
  "event": "mountpoint-info",
  "streams": [
     {
        "id": "Ababagalamaga",
        "index": 1,
        "audioport": 8783,
        "videoport": 8712,
        "stats": {
           "min": 0.0,
           "max": 0.0,
           "cur": 0.0,
           "avg": 0.0
        },
        "frame": {
           "width": 0,
           "height": 0,
           "fps": 0,
           "key-distance": 0
        },
        "session": {
           "webrtc-active": 1,
           "autoswitch-enabled": 1,
           "remb-avg": 0
        }
     },
     {
        "id": "Ababagalamaga",
        "index": 2,
        "audioport": 8346,
        "videoport": 8228,
        "stats": {
           "min": 0.0,
           "max": 0.0,
           "cur": 0.0,
           "avg": 0.0
        },
        "frame": {
           "width": 0,
           "height": 0,
           "fps": 0,
           "key-distance": 0
        },
        "session": {
           "webrtc-active": 0,
           "autoswitch-enabled": 1,
           "remb-avg": 0
        }
     }
  ],
  "config": {
     "source_avg_time": 10,
     "remb_avg_time": 3,
     "session_info_update_time": 10
  }
 }
}
```

**Comment by kris-lab** [comment]
@njam in general could you maybe suggest better naming for config file param + event name etc?

**Comment by njam** [comment]
Maybe "stats_avg_duration" instead of "source_avg_time"?

**Comment by kris-lab** [comment]
self merging. need this for #50

**Pull request merged**
