### PR TITLE
Fixes for pick-up the right stream based on REMB

### PR DESCRIPTION
**Pull request by kris-lab**
As investigated with @zazabe there are some bugs in the `cm_rtpbcast_pick_source`.

Also see related: https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/91

### CODE REVIEW

**Comment by kris-lab** [comment]
@zazabe as promised see
- lowest quality (2222kbits, REMB: 1917kbits) [lowest](https://cloud.githubusercontent.com/assets/1843523/15626383/ee09b474-24c3-11e6-8dea-b9a5cd85f92b.png)
- middle quality (3333kbits, REMB: 4345kbits) [middle](https://cloud.githubusercontent.com/assets/1843523/15626389/117a554e-24c4-11e6-920c-5a516d35051e.png)
- best quality (5000kbits, REMB: 6195kbits) [best](https://cloud.githubusercontent.com/assets/1843523/15626390/117bb42a-24c4-11e6-9026-dd1ab1f1b4cf.png)

cc @njam

**Comment by zazabe** [comment]
I thought about the auto-switch, should we rather implement it in the client side?
I see some advantages: easy to debug/maintain, could be based on the REMB, but also the playback FPS or even the animation frame FPS... wdyt?

**Comment by kris-lab** [comment]
In general I agree with this idea. This concept was raised for a few times already. Let's maybe @njam @zazabe discuss and agree on next steps?

**Comment by njam** [comment]
Doing it on the client side is definitely an option. Let's fix the auto switching nevertheless.

**Comment by kris-lab** [comment]
The `pick-up` logic:
- it assumes that streams are stored from the high bitrate (index=0) to the lowest bitrate (index=N)
- it loops from the highest to lowest and picks the first stream with current bitrate lower than REMB received from the browser.

**Comment by kris-lab** [comment]
Known issues:
- it is possible that the wrong stream will be chosen if REAL (calculated) bitrate of e.g. the highest quality stream is lower than the lower quality stream.

**Comment by njam** [comment]
Ah true, we assume the streams to be ordered by size. Stumbled upon this before.
I think it would be best if this was not necessary. Wdyt about ordering them automatically, indepedently of how they are configured?

What happens if REMB is lower than any of the streams bitrate?  I think we should then pick the lowest bitrate stream.

**Comment by kris-lab** [comment]
> What happens if REMB is lower than any of the streams bitrate? I think we should then pick the lowest bitrate stream.

I have updated my comment in meantime here https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/94#issuecomment-222628275

"if REMB is lower than the lowest stream bitrate then the lowest quality stream (bitrate) is chosen!"

**Comment by kris-lab** [comment]
> Wdyt about ordering them automatically, indepedently

Will try to implement...

**Comment by kris-lab** [comment]
Added descending sorting for current stream bitrate (highest bitrate first).

**Comment by kris-lab** [comment]
@zazabe would you like to test this changes on AWS?

**Comment by zazabe** [comment]
Yes, could be nice to have the REMB calculation too ;) is there any deb package available or should i build it from the source?

**Comment by kris-lab** [comment]
Please compile from source and test it first. Let me know if you need a help. The source is still on the AWS instance in user home directory; it needs just fetch changes, I guess.

**Comment by zazabe** [comment]
OK, this version is on AWS now.
The REMB is up to date in `mountpoint-info` with  `auto-switch: false`  and the switch is working according to the REMB value, lgtm.

**Comment by njam** [comment]
@zazabe could you verify it on AWS quickly?

**Comment by kris-lab** [comment]
as discussed I will release this code

**Pull request merged**
