### PR TITLE
Add super user support

### PR DESCRIPTION
**Pull request by kris-lab**
This should allow to upgrade plugin-handle session to be super user. 

Super user events:
- mountpoint create
- mountpoint destroy
- all mountpoint list every defined time period

TODO:
- [x] add "super-user" end point
- [x] trigger mountpoint-update event for each mountpoint create/destroy

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam @tomaszdurka could you have a look on README changes. It basically summarise what has been done for scaling.

**Comment by njam** [comment]
How about in the readme just describing what this plugin does, and not describe changes compared to the original "streaming" plugin? I think it's mostly like that already, but would make it a bit more understandable.

@tomaszdurka can you check the API definitions?

**Comment by kris-lab** [comment]
@njam agree

**Comment by kris-lab** [comment]
Follow up #67

**Pull request merged**
