### PR TITLE
Expose packet loss count in stats

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam that would it look like if we need this quick:
````json
"stats": {
    "audio": {
        "packet-loss-count": 501.0,
        "packet-loss": 0.04790419161676651,
        "bitrate": 491273.5924376457
    },
    "video": {
        "packet-loss-count": 62.0,
        "packet-loss": 0.032258064516129004,
        "bitrate": 35323.72630681433
    }
},
```

Otherwise we could rename `packet-loss` with `packet-loss-rate` but it will affect more repos. wdyt? @zazabe

**Comment by njam** [comment]
- Should be integer?
- Docu: Should not be averaged over a window, but total loss since stream start

**Comment by kris-lab** [comment]
@njam please re-review

**Comment by njam** [comment]
As discussed:
- Expose `packet-loss-rate`, and `packet-loss` for backwards compatibility
- Simplify code by keeping only 2 variables (packet-loss-rate, packet-loss-count)?

**Comment by zazabe** [comment]
fyi, on the client side, we use `packetLoss` for the rate and `packetsLost` (property name from `getStats()`) for the counter.

**Comment by zazabe** [comment]
I'm speaking about client side values retrieved/calculated with `getStats()`, not values received from `mountpoint-info`, but we could streamline them maybe...

**Comment by kris-lab** [comment]
@njam @zazabe could you review

**Comment by njam** [comment]
- Docu: I would only document `packet-loss-rate` then, as `packet-loss` is deprecated and only we use it.
 - Docu needs streamlining between audio+video
- Docu: In English it should be "packet loss" (the rate) and "packets lost" (the count), but not "packets loss"

**Comment by kris-lab** [comment]
ok @njam please have a look :)

**Comment by njam** [comment]
lgtm

**Pull request merged**
