### PR TITLE
Stream switching: allow to set source manually

### PR DESCRIPTION
**Pull request by kris-lab**
Currently there is auto source switching based on REMBs  and RTP average bitrate. I would suggest to implement new event called `switch-source` which would allow to disable auto switching and stick to specific source?

Request:
```js
{
  id: "streamChannelKey",
  streamSource: <int>
  ...
}
```

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam fyi I have added `source-switch` support (currently it conflicts with auto-switch which must be somehow configurable)

**Comment by kris-lab** [comment]
Request which changes `mountpoint-source`:

It working within browser console if used with `streamingtest.js` example:
```js
streaming.send({"message": { "request": "switch-source", index: 1 }})
```
`index` is an position in the array of sources. `index` -> `0` means `autoswitch` based on REMB is enabled

You can use `list` command to find out `mountpoints` and `sources` on your session:
```js
streaming.send({"message": { "request": "list" }})
```
Response of current mountpoints with sources
```js
         "list": [
            {
               "id": "111",
               "name": "111",
               "description": "111",
               "streams": [
                  {
                     "audioport": 8780,
                     "videoport": 8617,
                     "stats": {
                        "min": 138640.02150214222,
                        "max": 167213.56446396073,
                        "cur": 167002.49582007321,
                        "avg": 163128.59614126771
                     }
                  },
                  {
                     "audioport": 8859,
                     "videoport": 8919,
                     "stats": {
                        "min": 168644.74289541884,
                        "max": 171544.75224500845,
                        "cur": 170863.58924529309,
                        "avg": 170596.43731325402
                     }
                  }
               ]
            }
         ]
```

**Comment by landswellsong** [comment]
@kris-lab merging, but I have a couple of things to say:
1. I don't like the: 
```
something=TRUE;
...
something=FALSE;
```
Logic, at the least it will do nothing, at most, the assignment is not protected by mutex and as far as I understand, the operation is not atomic. I'll follow up with a commit correcting those.

2. This chance of condition:
```
-			if((guint)mp->sources->len <= index_value) {
+			if((mp->sources->len - index_value) < 0) {
```
What is the reason behind it?

**Comment by kris-lab** [comment]
Agree that line by line it does nothing. But we use blocking mutex in between? Well I copy this approach from janus `session->paused = TRUE; .. session->paused = FALSE;` e.g. on `switch` and other places. I think in multithreading env it makes sense?

**Comment by landswellsong** [comment]
@kris-lab I'll see to it, just need these all merged first so that they don't conflict with keyframe detector. Maybe I am wrong though, need to think.

**Comment by kris-lab** [comment]
ok, please merge! all is tested and working

**Pull request merged**
