### PR TITLE
Improve stats

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam wanna have a look?

**Comment by njam** [comment]
Should we drop "min", "max" and "avg" in the code to simplify?

**Comment by kris-lab** [comment]
About the stats. I am not sure is it good to delete this code. I have noticed there are people which use this plugin. Maybe we should keep it?

**Comment by kris-lab** [comment]
@njam fyi

**Comment by njam** [comment]
Description below "Stream definition for responses" needs to be updated.

**Comment by kris-lab** [comment]
ok, will do it #66

**Pull request merged**
