### PR TITLE
Update janus

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by njam** [comment]
We need a way to verify that a janus-gateway upgrade works with our plugins, and our application.
Best way I can think of is to mount all these repos into an application VM, build them, then do acceptance testing.
wdyt?

**Comment by ppp0** [comment]
Agree. Building in the way we're wanting is actually being handled optimally by the [current Janus puppet module](https://github.com/cargomedia/puppet-packages/tree/76a059945233011beb0b98add5ac4bb3f67d3f05/modules/janus) (due to be replaced by DEBs)

May be we can reuse this separately do do the acceptance tests

**Comment by njam** [comment]
@kris-lab closeable?

**Pull request closed without merging**
