### PR TITLE
Prettify readme

### PR DESCRIPTION
**Pull request by kris-lab**
- [x] remove comparisons with native plugin
- [x] add better overall description
- [x] add all end points definition

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam what about this changes? there is not much to add tbh. I have removed mainly the comparison between native/custom plugin.

**Comment by njam** [comment]
This list as an introduction is a bit difficult to read (16 bullet points :D). How about writing 2-3 sentences about what the plugin does, and then going into more details about the most important things:
- 1-to-many and RTP-to-WebRTC streaming
- Multiple streams per mountpoint with different qualities/resolutions
- Manual or auto-switching of these streams per client
- Recording of streams
- Thumbnails of streams

**Comment by kris-lab** [comment]
Ok, as you suggested I keep it short and abstracted :)

@njam wdyt?

**Comment by njam** [comment]
lgtm - @zazabe wanna double check?

**Comment by zazabe** [comment]
lgtm

**Pull request merged**
