### PR TITLE
janus rtpbroadcast: check packet loss metric

### PR DESCRIPTION
**Pull request by kris-lab**
screen shot 2016-05-06 at 01 05 02
screen shot 2016-05-06 at 01 05 10

"packet-loss" value "1" is reported over WebSocket, so probably a problem in the rtpbroadcast plugin.

### CODE REVIEW

**Comment by kris-lab** [comment]
I have working solution, but there is still very temporary issue with calculation when overflow occurs:
````
                            "stats": {
                                "audio": {
                                    "packet-loss": 0.0019920318725099584,
                                    "bitrate": 528121.48902517
                                },
                                "video": {
                                    "packet-loss": 0.9999999376004557,
                                    "bitrate": 1495733.5820154718
                                }
                            },
```
It estimate value of loss `~0.99` for single statistics interval...

**Comment by njam** [comment]
This will probably be wrong because `max_seq_since_last_avg` has been reset, but not `last_avg_seq`?
```
guint32 den = st->max_seq_since_last_avg - st->last_avg_seq + 1;
```
`last_avg_seq` should be reset at the same time maybe (`-65535`)?

**Comment by kris-lab** [comment]
I re-did a bit the logic. It is more accurate now. I have noticed that previous logic could calculate minus values and values more that 100%!

**Comment by kris-lab** [comment]
All tested locally with simulator and real streams. Should be fine.

**Comment by kris-lab** [comment]
@njam wdyt?

**Comment by njam** [comment]
ok - setting it to 0 is not fully correct, but if it happens only every 10 minutes it's not big an issues.

**Comment by kris-lab** [comment]
Hope it works on production similar to my local setup. I haven't noticed any issues over 60minutes of streaming.

**Comment by kris-lab** [comment]
Production works fine!

**Pull request merged**
