### PR TITLE
Keyframe cont of #13

### PR DESCRIPTION
**Pull request by kris-lab**
TODO:
- [x] frame params (width/height)
- [x] FPS
- [x] key frame distance
- [x] `list` action: marks stream/source if current websocket session is receiving via WebRTC
- [x] update readme
- [x] adjust `switch-source` action with scheduler
- [x] adjust `switch` action with scheduler
- [x] new media event: for subscriber: `switch-source=done` (via session transport)

### CODE REVIEW

**Comment by kris-lab** [comment]
Added frames (width/height) params per source to the stats:
````
                  {
                     "audioport": 8408,
                     "videoport": 8202,
                     "width": 640,
                     "height": 480,
                     "stats": {
                        "min": 954786.6314359809,
                        "max": 956877.02348645788,
                        "cur": 956055.31308432366,
                        "avg": 956075.72260409046
                     }
                  },
```

**Comment by kris-lab** [comment]
@njam finally I have found the way to push any messages from the `plugin` to connected `session`. That means we can send anything, anytime to the session `id/handler`. Since now the message was always the `response` to the `request`. Currently I have introduced new `media` event similar to `webrtcup`, `hangup` etc. but nested into the `rtpbrodacast` plugin. New event sends update to the client if `stream` or `mountpoint` has changed. It is send from the scheduler means the `autoswitch` logic or requested `switch`, `switch-source` will trigger it by queuing `switch` request into `scheduler`.

**Comment by njam** [comment]
:+1:

**Comment by kris-lab** [comment]
Self merging

**Pull request merged**
